// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.19.4
// source: goods.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 添加购物车
type AddShopCarReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId  int64 `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	GoodsId int64 `protobuf:"varint,2,opt,name=GoodsId,proto3" json:"GoodsId,omitempty"`
	Num     int64 `protobuf:"varint,3,opt,name=Num,proto3" json:"Num,omitempty"`
}

func (x *AddShopCarReq) Reset() {
	*x = AddShopCarReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_goods_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddShopCarReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddShopCarReq) ProtoMessage() {}

func (x *AddShopCarReq) ProtoReflect() protoreflect.Message {
	mi := &file_goods_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddShopCarReq.ProtoReflect.Descriptor instead.
func (*AddShopCarReq) Descriptor() ([]byte, []int) {
	return file_goods_proto_rawDescGZIP(), []int{0}
}

func (x *AddShopCarReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *AddShopCarReq) GetGoodsId() int64 {
	if x != nil {
		return x.GoodsId
	}
	return 0
}

func (x *AddShopCarReq) GetNum() int64 {
	if x != nil {
		return x.Num
	}
	return 0
}

type AddShopCarResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AddShopCarResp) Reset() {
	*x = AddShopCarResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_goods_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddShopCarResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddShopCarResp) ProtoMessage() {}

func (x *AddShopCarResp) ProtoReflect() protoreflect.Message {
	mi := &file_goods_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddShopCarResp.ProtoReflect.Descriptor instead.
func (*AddShopCarResp) Descriptor() ([]byte, []int) {
	return file_goods_proto_rawDescGZIP(), []int{1}
}

// 增加购物车记载数量
type AddShopCarNumReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId  int64 `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	GoodsId int64 `protobuf:"varint,2,opt,name=GoodsId,proto3" json:"GoodsId,omitempty"`
}

func (x *AddShopCarNumReq) Reset() {
	*x = AddShopCarNumReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_goods_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddShopCarNumReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddShopCarNumReq) ProtoMessage() {}

func (x *AddShopCarNumReq) ProtoReflect() protoreflect.Message {
	mi := &file_goods_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddShopCarNumReq.ProtoReflect.Descriptor instead.
func (*AddShopCarNumReq) Descriptor() ([]byte, []int) {
	return file_goods_proto_rawDescGZIP(), []int{2}
}

func (x *AddShopCarNumReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *AddShopCarNumReq) GetGoodsId() int64 {
	if x != nil {
		return x.GoodsId
	}
	return 0
}

type AddShopCarNumResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AddShopCarNumResp) Reset() {
	*x = AddShopCarNumResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_goods_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddShopCarNumResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddShopCarNumResp) ProtoMessage() {}

func (x *AddShopCarNumResp) ProtoReflect() protoreflect.Message {
	mi := &file_goods_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddShopCarNumResp.ProtoReflect.Descriptor instead.
func (*AddShopCarNumResp) Descriptor() ([]byte, []int) {
	return file_goods_proto_rawDescGZIP(), []int{3}
}

// 减少购物车记载数量
type PopShopCarNumReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId  int64 `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	GoodsId int64 `protobuf:"varint,2,opt,name=GoodsId,proto3" json:"GoodsId,omitempty"`
}

func (x *PopShopCarNumReq) Reset() {
	*x = PopShopCarNumReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_goods_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PopShopCarNumReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PopShopCarNumReq) ProtoMessage() {}

func (x *PopShopCarNumReq) ProtoReflect() protoreflect.Message {
	mi := &file_goods_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PopShopCarNumReq.ProtoReflect.Descriptor instead.
func (*PopShopCarNumReq) Descriptor() ([]byte, []int) {
	return file_goods_proto_rawDescGZIP(), []int{4}
}

func (x *PopShopCarNumReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *PopShopCarNumReq) GetGoodsId() int64 {
	if x != nil {
		return x.GoodsId
	}
	return 0
}

type PopShopCarNumResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PopShopCarNumResp) Reset() {
	*x = PopShopCarNumResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_goods_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PopShopCarNumResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PopShopCarNumResp) ProtoMessage() {}

func (x *PopShopCarNumResp) ProtoReflect() protoreflect.Message {
	mi := &file_goods_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PopShopCarNumResp.ProtoReflect.Descriptor instead.
func (*PopShopCarNumResp) Descriptor() ([]byte, []int) {
	return file_goods_proto_rawDescGZIP(), []int{5}
}

// 直接修改购物车数量
type UpdateShopCarNumReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId  int64 `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	GoodsId int64 `protobuf:"varint,2,opt,name=GoodsId,proto3" json:"GoodsId,omitempty"`
	Num     int64 `protobuf:"varint,3,opt,name=Num,proto3" json:"Num,omitempty"`
}

func (x *UpdateShopCarNumReq) Reset() {
	*x = UpdateShopCarNumReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_goods_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateShopCarNumReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateShopCarNumReq) ProtoMessage() {}

func (x *UpdateShopCarNumReq) ProtoReflect() protoreflect.Message {
	mi := &file_goods_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateShopCarNumReq.ProtoReflect.Descriptor instead.
func (*UpdateShopCarNumReq) Descriptor() ([]byte, []int) {
	return file_goods_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateShopCarNumReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UpdateShopCarNumReq) GetGoodsId() int64 {
	if x != nil {
		return x.GoodsId
	}
	return 0
}

func (x *UpdateShopCarNumReq) GetNum() int64 {
	if x != nil {
		return x.Num
	}
	return 0
}

type UpdateShopCarNumResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateShopCarNumResp) Reset() {
	*x = UpdateShopCarNumResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_goods_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateShopCarNumResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateShopCarNumResp) ProtoMessage() {}

func (x *UpdateShopCarNumResp) ProtoReflect() protoreflect.Message {
	mi := &file_goods_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateShopCarNumResp.ProtoReflect.Descriptor instead.
func (*UpdateShopCarNumResp) Descriptor() ([]byte, []int) {
	return file_goods_proto_rawDescGZIP(), []int{7}
}

// 清空购物车
type CleanShopCarReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId int64 `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
}

func (x *CleanShopCarReq) Reset() {
	*x = CleanShopCarReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_goods_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CleanShopCarReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CleanShopCarReq) ProtoMessage() {}

func (x *CleanShopCarReq) ProtoReflect() protoreflect.Message {
	mi := &file_goods_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CleanShopCarReq.ProtoReflect.Descriptor instead.
func (*CleanShopCarReq) Descriptor() ([]byte, []int) {
	return file_goods_proto_rawDescGZIP(), []int{8}
}

func (x *CleanShopCarReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type CleanShopCarResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CleanShopCarResp) Reset() {
	*x = CleanShopCarResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_goods_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CleanShopCarResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CleanShopCarResp) ProtoMessage() {}

func (x *CleanShopCarResp) ProtoReflect() protoreflect.Message {
	mi := &file_goods_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CleanShopCarResp.ProtoReflect.Descriptor instead.
func (*CleanShopCarResp) Descriptor() ([]byte, []int) {
	return file_goods_proto_rawDescGZIP(), []int{9}
}

// 获取购物车未支付商品的总价
type GetShopCarAllPriceReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId int64 `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
}

func (x *GetShopCarAllPriceReq) Reset() {
	*x = GetShopCarAllPriceReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_goods_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetShopCarAllPriceReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShopCarAllPriceReq) ProtoMessage() {}

func (x *GetShopCarAllPriceReq) ProtoReflect() protoreflect.Message {
	mi := &file_goods_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShopCarAllPriceReq.ProtoReflect.Descriptor instead.
func (*GetShopCarAllPriceReq) Descriptor() ([]byte, []int) {
	return file_goods_proto_rawDescGZIP(), []int{10}
}

func (x *GetShopCarAllPriceReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetShopCarAllPriceResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Price float32 `protobuf:"fixed32,2,opt,name=price,proto3" json:"price,omitempty"`
}

func (x *GetShopCarAllPriceResp) Reset() {
	*x = GetShopCarAllPriceResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_goods_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetShopCarAllPriceResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShopCarAllPriceResp) ProtoMessage() {}

func (x *GetShopCarAllPriceResp) ProtoReflect() protoreflect.Message {
	mi := &file_goods_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShopCarAllPriceResp.ProtoReflect.Descriptor instead.
func (*GetShopCarAllPriceResp) Descriptor() ([]byte, []int) {
	return file_goods_proto_rawDescGZIP(), []int{11}
}

func (x *GetShopCarAllPriceResp) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

type ShopCarList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GoodsName  string  `protobuf:"bytes,1,opt,name=goodsName,proto3" json:"goodsName,omitempty"`
	GoodsPrice float32 `protobuf:"fixed32,2,opt,name=goodsPrice,proto3" json:"goodsPrice,omitempty"`
	GrandName  string  `protobuf:"bytes,3,opt,name=grandName,proto3" json:"grandName,omitempty"`
	GoodsUrl   string  `protobuf:"bytes,4,opt,name=goodsUrl,proto3" json:"goodsUrl,omitempty"`
	GoodsDesc  string  `protobuf:"bytes,5,opt,name=goodsDesc,proto3" json:"goodsDesc,omitempty"`
	Num        int64   `protobuf:"varint,6,opt,name=num,proto3" json:"num,omitempty"`
	Id         int64   `protobuf:"varint,7,opt,name=id,proto3" json:"id,omitempty"`
	ShopName   string  `protobuf:"bytes,9,opt,name=shopName,proto3" json:"shopName,omitempty"`
	Color      string  `protobuf:"bytes,10,opt,name=color,proto3" json:"color,omitempty"`
	Size       string  `protobuf:"bytes,11,opt,name=size,proto3" json:"size,omitempty"`
	Material   string  `protobuf:"bytes,12,opt,name=material,proto3" json:"material,omitempty"`
}

func (x *ShopCarList) Reset() {
	*x = ShopCarList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_goods_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShopCarList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShopCarList) ProtoMessage() {}

func (x *ShopCarList) ProtoReflect() protoreflect.Message {
	mi := &file_goods_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShopCarList.ProtoReflect.Descriptor instead.
func (*ShopCarList) Descriptor() ([]byte, []int) {
	return file_goods_proto_rawDescGZIP(), []int{12}
}

func (x *ShopCarList) GetGoodsName() string {
	if x != nil {
		return x.GoodsName
	}
	return ""
}

func (x *ShopCarList) GetGoodsPrice() float32 {
	if x != nil {
		return x.GoodsPrice
	}
	return 0
}

func (x *ShopCarList) GetGrandName() string {
	if x != nil {
		return x.GrandName
	}
	return ""
}

func (x *ShopCarList) GetGoodsUrl() string {
	if x != nil {
		return x.GoodsUrl
	}
	return ""
}

func (x *ShopCarList) GetGoodsDesc() string {
	if x != nil {
		return x.GoodsDesc
	}
	return ""
}

func (x *ShopCarList) GetNum() int64 {
	if x != nil {
		return x.Num
	}
	return 0
}

func (x *ShopCarList) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ShopCarList) GetShopName() string {
	if x != nil {
		return x.ShopName
	}
	return ""
}

func (x *ShopCarList) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

func (x *ShopCarList) GetSize() string {
	if x != nil {
		return x.Size
	}
	return ""
}

func (x *ShopCarList) GetMaterial() string {
	if x != nil {
		return x.Material
	}
	return ""
}

// 获取购物车列表
type UserShopCarListReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId int64 `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
}

func (x *UserShopCarListReq) Reset() {
	*x = UserShopCarListReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_goods_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserShopCarListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserShopCarListReq) ProtoMessage() {}

func (x *UserShopCarListReq) ProtoReflect() protoreflect.Message {
	mi := &file_goods_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserShopCarListReq.ProtoReflect.Descriptor instead.
func (*UserShopCarListReq) Descriptor() ([]byte, []int) {
	return file_goods_proto_rawDescGZIP(), []int{13}
}

func (x *UserShopCarListReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type UserShopCarListResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List []*ShopCarList `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
}

func (x *UserShopCarListResp) Reset() {
	*x = UserShopCarListResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_goods_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserShopCarListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserShopCarListResp) ProtoMessage() {}

func (x *UserShopCarListResp) ProtoReflect() protoreflect.Message {
	mi := &file_goods_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserShopCarListResp.ProtoReflect.Descriptor instead.
func (*UserShopCarListResp) Descriptor() ([]byte, []int) {
	return file_goods_proto_rawDescGZIP(), []int{14}
}

func (x *UserShopCarListResp) GetList() []*ShopCarList {
	if x != nil {
		return x.List
	}
	return nil
}

// 根据商品名查redis查
type UserSearchShopCarByNameReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name   string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	UserId int64  `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
}

func (x *UserSearchShopCarByNameReq) Reset() {
	*x = UserSearchShopCarByNameReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_goods_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserSearchShopCarByNameReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserSearchShopCarByNameReq) ProtoMessage() {}

func (x *UserSearchShopCarByNameReq) ProtoReflect() protoreflect.Message {
	mi := &file_goods_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserSearchShopCarByNameReq.ProtoReflect.Descriptor instead.
func (*UserSearchShopCarByNameReq) Descriptor() ([]byte, []int) {
	return file_goods_proto_rawDescGZIP(), []int{15}
}

func (x *UserSearchShopCarByNameReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserSearchShopCarByNameReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type UserSearchShopCarByNameResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List []*ShopCarList `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
}

func (x *UserSearchShopCarByNameResp) Reset() {
	*x = UserSearchShopCarByNameResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_goods_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserSearchShopCarByNameResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserSearchShopCarByNameResp) ProtoMessage() {}

func (x *UserSearchShopCarByNameResp) ProtoReflect() protoreflect.Message {
	mi := &file_goods_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserSearchShopCarByNameResp.ProtoReflect.Descriptor instead.
func (*UserSearchShopCarByNameResp) Descriptor() ([]byte, []int) {
	return file_goods_proto_rawDescGZIP(), []int{16}
}

func (x *UserSearchShopCarByNameResp) GetList() []*ShopCarList {
	if x != nil {
		return x.List
	}
	return nil
}

// 删除某项购物车数据
type DelOneShopCarDataReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId  int64 `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	GoodsId int64 `protobuf:"varint,2,opt,name=GoodsId,proto3" json:"GoodsId,omitempty"`
}

func (x *DelOneShopCarDataReq) Reset() {
	*x = DelOneShopCarDataReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_goods_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DelOneShopCarDataReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelOneShopCarDataReq) ProtoMessage() {}

func (x *DelOneShopCarDataReq) ProtoReflect() protoreflect.Message {
	mi := &file_goods_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelOneShopCarDataReq.ProtoReflect.Descriptor instead.
func (*DelOneShopCarDataReq) Descriptor() ([]byte, []int) {
	return file_goods_proto_rawDescGZIP(), []int{17}
}

func (x *DelOneShopCarDataReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *DelOneShopCarDataReq) GetGoodsId() int64 {
	if x != nil {
		return x.GoodsId
	}
	return 0
}

type DelOneShopCarDataResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DelOneShopCarDataResp) Reset() {
	*x = DelOneShopCarDataResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_goods_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DelOneShopCarDataResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelOneShopCarDataResp) ProtoMessage() {}

func (x *DelOneShopCarDataResp) ProtoReflect() protoreflect.Message {
	mi := &file_goods_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelOneShopCarDataResp.ProtoReflect.Descriptor instead.
func (*DelOneShopCarDataResp) Descriptor() ([]byte, []int) {
	return file_goods_proto_rawDescGZIP(), []int{18}
}

// 首页搜索列表
type WelcomeSearchShopListReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BrandName string `protobuf:"bytes,1,opt,name=brandName,proto3" json:"brandName,omitempty"`
	Page      int64  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize  int64  `protobuf:"varint,3,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
}

func (x *WelcomeSearchShopListReq) Reset() {
	*x = WelcomeSearchShopListReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_goods_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WelcomeSearchShopListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WelcomeSearchShopListReq) ProtoMessage() {}

func (x *WelcomeSearchShopListReq) ProtoReflect() protoreflect.Message {
	mi := &file_goods_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WelcomeSearchShopListReq.ProtoReflect.Descriptor instead.
func (*WelcomeSearchShopListReq) Descriptor() ([]byte, []int) {
	return file_goods_proto_rawDescGZIP(), []int{19}
}

func (x *WelcomeSearchShopListReq) GetBrandName() string {
	if x != nil {
		return x.BrandName
	}
	return ""
}

func (x *WelcomeSearchShopListReq) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *WelcomeSearchShopListReq) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type WelcomeSearchShopListResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List []*WelcomeSearchShopList `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
}

func (x *WelcomeSearchShopListResp) Reset() {
	*x = WelcomeSearchShopListResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_goods_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WelcomeSearchShopListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WelcomeSearchShopListResp) ProtoMessage() {}

func (x *WelcomeSearchShopListResp) ProtoReflect() protoreflect.Message {
	mi := &file_goods_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WelcomeSearchShopListResp.ProtoReflect.Descriptor instead.
func (*WelcomeSearchShopListResp) Descriptor() ([]byte, []int) {
	return file_goods_proto_rawDescGZIP(), []int{20}
}

func (x *WelcomeSearchShopListResp) GetList() []*WelcomeSearchShopList {
	if x != nil {
		return x.List
	}
	return nil
}

type WelcomeSearchShopList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BrandLogo        string  `protobuf:"bytes,1,opt,name=BrandLogo,proto3" json:"BrandLogo,omitempty"`
	GoodsName        string  `protobuf:"bytes,2,opt,name=GoodsName,proto3" json:"GoodsName,omitempty"`
	BrandDescription string  `protobuf:"bytes,3,opt,name=BrandDescription,proto3" json:"BrandDescription,omitempty"`
	GoodsPrice       float32 `protobuf:"fixed32,4,opt,name=GoodsPrice,proto3" json:"GoodsPrice,omitempty"`
	BrandName        string  `protobuf:"bytes,5,opt,name=BrandName,proto3" json:"BrandName,omitempty"`
	GoodsUrl         string  `protobuf:"bytes,6,opt,name=GoodsUrl,proto3" json:"GoodsUrl,omitempty"`
	GoodsDesc        string  `protobuf:"bytes,7,opt,name=GoodsDesc,proto3" json:"GoodsDesc,omitempty"`
	GoodsStock       int64   `protobuf:"varint,8,opt,name=GoodsStock,proto3" json:"GoodsStock,omitempty"`
	GoodsStatus      int64   `protobuf:"varint,9,opt,name=GoodsStatus,proto3" json:"GoodsStatus,omitempty"`
	Sales            int64   `protobuf:"varint,10,opt,name=Sales,proto3" json:"Sales,omitempty"`
}

func (x *WelcomeSearchShopList) Reset() {
	*x = WelcomeSearchShopList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_goods_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WelcomeSearchShopList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WelcomeSearchShopList) ProtoMessage() {}

func (x *WelcomeSearchShopList) ProtoReflect() protoreflect.Message {
	mi := &file_goods_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WelcomeSearchShopList.ProtoReflect.Descriptor instead.
func (*WelcomeSearchShopList) Descriptor() ([]byte, []int) {
	return file_goods_proto_rawDescGZIP(), []int{21}
}

func (x *WelcomeSearchShopList) GetBrandLogo() string {
	if x != nil {
		return x.BrandLogo
	}
	return ""
}

func (x *WelcomeSearchShopList) GetGoodsName() string {
	if x != nil {
		return x.GoodsName
	}
	return ""
}

func (x *WelcomeSearchShopList) GetBrandDescription() string {
	if x != nil {
		return x.BrandDescription
	}
	return ""
}

func (x *WelcomeSearchShopList) GetGoodsPrice() float32 {
	if x != nil {
		return x.GoodsPrice
	}
	return 0
}

func (x *WelcomeSearchShopList) GetBrandName() string {
	if x != nil {
		return x.BrandName
	}
	return ""
}

func (x *WelcomeSearchShopList) GetGoodsUrl() string {
	if x != nil {
		return x.GoodsUrl
	}
	return ""
}

func (x *WelcomeSearchShopList) GetGoodsDesc() string {
	if x != nil {
		return x.GoodsDesc
	}
	return ""
}

func (x *WelcomeSearchShopList) GetGoodsStock() int64 {
	if x != nil {
		return x.GoodsStock
	}
	return 0
}

func (x *WelcomeSearchShopList) GetGoodsStatus() int64 {
	if x != nil {
		return x.GoodsStatus
	}
	return 0
}

func (x *WelcomeSearchShopList) GetSales() int64 {
	if x != nil {
		return x.Sales
	}
	return 0
}

// 商品详情
type GoodsDetailReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GoodsId int64 `protobuf:"varint,1,opt,name=goods_id,json=goodsId,proto3" json:"goods_id,omitempty"` // 商品ID
}

func (x *GoodsDetailReq) Reset() {
	*x = GoodsDetailReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_goods_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GoodsDetailReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoodsDetailReq) ProtoMessage() {}

func (x *GoodsDetailReq) ProtoReflect() protoreflect.Message {
	mi := &file_goods_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoodsDetailReq.ProtoReflect.Descriptor instead.
func (*GoodsDetailReq) Descriptor() ([]byte, []int) {
	return file_goods_proto_rawDescGZIP(), []int{22}
}

func (x *GoodsDetailReq) GetGoodsId() int64 {
	if x != nil {
		return x.GoodsId
	}
	return 0
}

type GoodsDetailResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GoodsDetail *GoodsDetail `protobuf:"bytes,1,opt,name=goodsDetail,proto3" json:"goodsDetail,omitempty"`
}

func (x *GoodsDetailResp) Reset() {
	*x = GoodsDetailResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_goods_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GoodsDetailResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoodsDetailResp) ProtoMessage() {}

func (x *GoodsDetailResp) ProtoReflect() protoreflect.Message {
	mi := &file_goods_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoodsDetailResp.ProtoReflect.Descriptor instead.
func (*GoodsDetailResp) Descriptor() ([]byte, []int) {
	return file_goods_proto_rawDescGZIP(), []int{23}
}

func (x *GoodsDetailResp) GetGoodsDetail() *GoodsDetail {
	if x != nil {
		return x.GoodsDetail
	}
	return nil
}

type GoodsDetail struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GoodsId     int64   `protobuf:"varint,1,opt,name=goods_id,json=goodsId,proto3" json:"goods_id,omitempty"`
	GoodsName   string  `protobuf:"bytes,2,opt,name=goods_name,json=goodsName,proto3" json:"goods_name,omitempty"`
	GoodsPrice  float64 `protobuf:"fixed64,3,opt,name=goods_price,json=goodsPrice,proto3" json:"goods_price,omitempty"`
	GoodsDesc   string  `protobuf:"bytes,4,opt,name=goods_desc,json=goodsDesc,proto3" json:"goods_desc,omitempty"`
	ImageUrl    string  `protobuf:"bytes,5,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	SliderImage string  `protobuf:"bytes,6,opt,name=slider_image,json=sliderImage,proto3" json:"slider_image,omitempty"`
}

func (x *GoodsDetail) Reset() {
	*x = GoodsDetail{}
	if protoimpl.UnsafeEnabled {
		mi := &file_goods_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GoodsDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoodsDetail) ProtoMessage() {}

func (x *GoodsDetail) ProtoReflect() protoreflect.Message {
	mi := &file_goods_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoodsDetail.ProtoReflect.Descriptor instead.
func (*GoodsDetail) Descriptor() ([]byte, []int) {
	return file_goods_proto_rawDescGZIP(), []int{24}
}

func (x *GoodsDetail) GetGoodsId() int64 {
	if x != nil {
		return x.GoodsId
	}
	return 0
}

func (x *GoodsDetail) GetGoodsName() string {
	if x != nil {
		return x.GoodsName
	}
	return ""
}

func (x *GoodsDetail) GetGoodsPrice() float64 {
	if x != nil {
		return x.GoodsPrice
	}
	return 0
}

func (x *GoodsDetail) GetGoodsDesc() string {
	if x != nil {
		return x.GoodsDesc
	}
	return ""
}

func (x *GoodsDetail) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *GoodsDetail) GetSliderImage() string {
	if x != nil {
		return x.SliderImage
	}
	return ""
}

// 店铺详情
type ShopDetailReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GoodsId int64 `protobuf:"varint,1,opt,name=goods_id,json=goodsId,proto3" json:"goods_id,omitempty"` // 商店ID
}

func (x *ShopDetailReq) Reset() {
	*x = ShopDetailReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_goods_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShopDetailReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShopDetailReq) ProtoMessage() {}

func (x *ShopDetailReq) ProtoReflect() protoreflect.Message {
	mi := &file_goods_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShopDetailReq.ProtoReflect.Descriptor instead.
func (*ShopDetailReq) Descriptor() ([]byte, []int) {
	return file_goods_proto_rawDescGZIP(), []int{25}
}

func (x *ShopDetailReq) GetGoodsId() int64 {
	if x != nil {
		return x.GoodsId
	}
	return 0
}

type ShopDetailResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ShopDetail *ShopDetail `protobuf:"bytes,1,opt,name=shopDetail,proto3" json:"shopDetail,omitempty"`
}

func (x *ShopDetailResp) Reset() {
	*x = ShopDetailResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_goods_proto_msgTypes[26]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShopDetailResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShopDetailResp) ProtoMessage() {}

func (x *ShopDetailResp) ProtoReflect() protoreflect.Message {
	mi := &file_goods_proto_msgTypes[26]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShopDetailResp.ProtoReflect.Descriptor instead.
func (*ShopDetailResp) Descriptor() ([]byte, []int) {
	return file_goods_proto_rawDescGZIP(), []int{26}
}

func (x *ShopDetailResp) GetShopDetail() *ShopDetail {
	if x != nil {
		return x.ShopDetail
	}
	return nil
}

type ShopDetail struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GoodsId     int64   `protobuf:"varint,1,opt,name=goods_id,json=goodsId,proto3" json:"goods_id,omitempty"`
	GoodsName   string  `protobuf:"bytes,2,opt,name=goods_name,json=goodsName,proto3" json:"goods_name,omitempty"`
	GoodsPrice  float32 `protobuf:"fixed32,3,opt,name=goods_price,json=goodsPrice,proto3" json:"goods_price,omitempty"`
	GoodsDesc   string  `protobuf:"bytes,4,opt,name=goods_desc,json=goodsDesc,proto3" json:"goods_desc,omitempty"`
	ShopName    string  `protobuf:"bytes,5,opt,name=shop_name,json=shopName,proto3" json:"shop_name,omitempty"`
	ShopDesc    string  `protobuf:"bytes,6,opt,name=shop_desc,json=shopDesc,proto3" json:"shop_desc,omitempty"`
	ShopLogo    string  `protobuf:"bytes,7,opt,name=shop_logo,json=shopLogo,proto3" json:"shop_logo,omitempty"`
	ShopPhone   string  `protobuf:"bytes,8,opt,name=shop_phone,json=shopPhone,proto3" json:"shop_phone,omitempty"`
	ShopAddress string  `protobuf:"bytes,9,opt,name=shop_address,json=shopAddress,proto3" json:"shop_address,omitempty"`
	ShopStatus  string  `protobuf:"bytes,10,opt,name=shop_status,json=shopStatus,proto3" json:"shop_status,omitempty"`
	ImageUrl    string  `protobuf:"bytes,11,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	SliderImage string  `protobuf:"bytes,12,opt,name=slider_image,json=sliderImage,proto3" json:"slider_image,omitempty"`
}

func (x *ShopDetail) Reset() {
	*x = ShopDetail{}
	if protoimpl.UnsafeEnabled {
		mi := &file_goods_proto_msgTypes[27]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShopDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShopDetail) ProtoMessage() {}

func (x *ShopDetail) ProtoReflect() protoreflect.Message {
	mi := &file_goods_proto_msgTypes[27]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShopDetail.ProtoReflect.Descriptor instead.
func (*ShopDetail) Descriptor() ([]byte, []int) {
	return file_goods_proto_rawDescGZIP(), []int{27}
}

func (x *ShopDetail) GetGoodsId() int64 {
	if x != nil {
		return x.GoodsId
	}
	return 0
}

func (x *ShopDetail) GetGoodsName() string {
	if x != nil {
		return x.GoodsName
	}
	return ""
}

func (x *ShopDetail) GetGoodsPrice() float32 {
	if x != nil {
		return x.GoodsPrice
	}
	return 0
}

func (x *ShopDetail) GetGoodsDesc() string {
	if x != nil {
		return x.GoodsDesc
	}
	return ""
}

func (x *ShopDetail) GetShopName() string {
	if x != nil {
		return x.ShopName
	}
	return ""
}

func (x *ShopDetail) GetShopDesc() string {
	if x != nil {
		return x.ShopDesc
	}
	return ""
}

func (x *ShopDetail) GetShopLogo() string {
	if x != nil {
		return x.ShopLogo
	}
	return ""
}

func (x *ShopDetail) GetShopPhone() string {
	if x != nil {
		return x.ShopPhone
	}
	return ""
}

func (x *ShopDetail) GetShopAddress() string {
	if x != nil {
		return x.ShopAddress
	}
	return ""
}

func (x *ShopDetail) GetShopStatus() string {
	if x != nil {
		return x.ShopStatus
	}
	return ""
}

func (x *ShopDetail) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *ShopDetail) GetSliderImage() string {
	if x != nil {
		return x.SliderImage
	}
	return ""
}

// 商品推荐
type GoodsPushReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GoodsPushReq) Reset() {
	*x = GoodsPushReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_goods_proto_msgTypes[28]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GoodsPushReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoodsPushReq) ProtoMessage() {}

func (x *GoodsPushReq) ProtoReflect() protoreflect.Message {
	mi := &file_goods_proto_msgTypes[28]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoodsPushReq.ProtoReflect.Descriptor instead.
func (*GoodsPushReq) Descriptor() ([]byte, []int) {
	return file_goods_proto_rawDescGZIP(), []int{28}
}

type GoodsPushResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List []*GoodsPush `protobuf:"bytes,1,rep,name=List,proto3" json:"List,omitempty"`
}

func (x *GoodsPushResp) Reset() {
	*x = GoodsPushResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_goods_proto_msgTypes[29]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GoodsPushResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoodsPushResp) ProtoMessage() {}

func (x *GoodsPushResp) ProtoReflect() protoreflect.Message {
	mi := &file_goods_proto_msgTypes[29]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoodsPushResp.ProtoReflect.Descriptor instead.
func (*GoodsPushResp) Descriptor() ([]byte, []int) {
	return file_goods_proto_rawDescGZIP(), []int{29}
}

func (x *GoodsPushResp) GetList() []*GoodsPush {
	if x != nil {
		return x.List
	}
	return nil
}

type GoodsPush struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GoodsId     int64   `protobuf:"varint,1,opt,name=goods_id,json=goodsId,proto3" json:"goods_id,omitempty"`
	GoodsName   string  `protobuf:"bytes,2,opt,name=goods_name,json=goodsName,proto3" json:"goods_name,omitempty"`
	GoodsPrice  float32 `protobuf:"fixed32,3,opt,name=goods_price,json=goodsPrice,proto3" json:"goods_price,omitempty"`
	BrandName   string  `protobuf:"bytes,4,opt,name=brand_name,json=brandName,proto3" json:"brand_name,omitempty"`
	GoodsUrl    string  `protobuf:"bytes,5,opt,name=goods_url,json=goodsUrl,proto3" json:"goods_url,omitempty"`
	SliderImage string  `protobuf:"bytes,6,opt,name=slider_image,json=sliderImage,proto3" json:"slider_image,omitempty"`
	Sales       int64   `protobuf:"varint,7,opt,name=sales,proto3" json:"sales,omitempty"`
	GoodsDesc   string  `protobuf:"bytes,8,opt,name=goods_desc,json=goodsDesc,proto3" json:"goods_desc,omitempty"`
}

func (x *GoodsPush) Reset() {
	*x = GoodsPush{}
	if protoimpl.UnsafeEnabled {
		mi := &file_goods_proto_msgTypes[30]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GoodsPush) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoodsPush) ProtoMessage() {}

func (x *GoodsPush) ProtoReflect() protoreflect.Message {
	mi := &file_goods_proto_msgTypes[30]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoodsPush.ProtoReflect.Descriptor instead.
func (*GoodsPush) Descriptor() ([]byte, []int) {
	return file_goods_proto_rawDescGZIP(), []int{30}
}

func (x *GoodsPush) GetGoodsId() int64 {
	if x != nil {
		return x.GoodsId
	}
	return 0
}

func (x *GoodsPush) GetGoodsName() string {
	if x != nil {
		return x.GoodsName
	}
	return ""
}

func (x *GoodsPush) GetGoodsPrice() float32 {
	if x != nil {
		return x.GoodsPrice
	}
	return 0
}

func (x *GoodsPush) GetBrandName() string {
	if x != nil {
		return x.BrandName
	}
	return ""
}

func (x *GoodsPush) GetGoodsUrl() string {
	if x != nil {
		return x.GoodsUrl
	}
	return ""
}

func (x *GoodsPush) GetSliderImage() string {
	if x != nil {
		return x.SliderImage
	}
	return ""
}

func (x *GoodsPush) GetSales() int64 {
	if x != nil {
		return x.Sales
	}
	return 0
}

func (x *GoodsPush) GetGoodsDesc() string {
	if x != nil {
		return x.GoodsDesc
	}
	return ""
}

// 首页搜索
type WelcomeSearchReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *WelcomeSearchReq) Reset() {
	*x = WelcomeSearchReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_goods_proto_msgTypes[31]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WelcomeSearchReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WelcomeSearchReq) ProtoMessage() {}

func (x *WelcomeSearchReq) ProtoReflect() protoreflect.Message {
	mi := &file_goods_proto_msgTypes[31]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WelcomeSearchReq.ProtoReflect.Descriptor instead.
func (*WelcomeSearchReq) Descriptor() ([]byte, []int) {
	return file_goods_proto_rawDescGZIP(), []int{31}
}

func (x *WelcomeSearchReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type WelcomeSearchResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id               int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	BrandName        string `protobuf:"bytes,2,opt,name=brandName,proto3" json:"brandName,omitempty"`
	BrandLogo        string `protobuf:"bytes,3,opt,name=brandLogo,proto3" json:"brandLogo,omitempty"`
	BrandDescription string `protobuf:"bytes,4,opt,name=brandDescription,proto3" json:"brandDescription,omitempty"`
}

func (x *WelcomeSearchResp) Reset() {
	*x = WelcomeSearchResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_goods_proto_msgTypes[32]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WelcomeSearchResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WelcomeSearchResp) ProtoMessage() {}

func (x *WelcomeSearchResp) ProtoReflect() protoreflect.Message {
	mi := &file_goods_proto_msgTypes[32]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WelcomeSearchResp.ProtoReflect.Descriptor instead.
func (*WelcomeSearchResp) Descriptor() ([]byte, []int) {
	return file_goods_proto_rawDescGZIP(), []int{32}
}

func (x *WelcomeSearchResp) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *WelcomeSearchResp) GetBrandName() string {
	if x != nil {
		return x.BrandName
	}
	return ""
}

func (x *WelcomeSearchResp) GetBrandLogo() string {
	if x != nil {
		return x.BrandLogo
	}
	return ""
}

func (x *WelcomeSearchResp) GetBrandDescription() string {
	if x != nil {
		return x.BrandDescription
	}
	return ""
}

// 热度值
type HotSearchReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Limit int64 `protobuf:"varint,1,opt,name=Limit,proto3" json:"Limit,omitempty"`
}

func (x *HotSearchReq) Reset() {
	*x = HotSearchReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_goods_proto_msgTypes[33]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HotSearchReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HotSearchReq) ProtoMessage() {}

func (x *HotSearchReq) ProtoReflect() protoreflect.Message {
	mi := &file_goods_proto_msgTypes[33]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HotSearchReq.ProtoReflect.Descriptor instead.
func (*HotSearchReq) Descriptor() ([]byte, []int) {
	return file_goods_proto_rawDescGZIP(), []int{33}
}

func (x *HotSearchReq) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type HotSearchResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List []*HotList `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
}

func (x *HotSearchResp) Reset() {
	*x = HotSearchResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_goods_proto_msgTypes[34]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HotSearchResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HotSearchResp) ProtoMessage() {}

func (x *HotSearchResp) ProtoReflect() protoreflect.Message {
	mi := &file_goods_proto_msgTypes[34]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HotSearchResp.ProtoReflect.Descriptor instead.
func (*HotSearchResp) Descriptor() ([]byte, []int) {
	return file_goods_proto_rawDescGZIP(), []int{34}
}

func (x *HotSearchResp) GetList() []*HotList {
	if x != nil {
		return x.List
	}
	return nil
}

type HotList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	BrandName string `protobuf:"bytes,2,opt,name=brandName,proto3" json:"brandName,omitempty"`
	Hot       int64  `protobuf:"varint,3,opt,name=hot,proto3" json:"hot,omitempty"`
}

func (x *HotList) Reset() {
	*x = HotList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_goods_proto_msgTypes[35]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HotList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HotList) ProtoMessage() {}

func (x *HotList) ProtoReflect() protoreflect.Message {
	mi := &file_goods_proto_msgTypes[35]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HotList.ProtoReflect.Descriptor instead.
func (*HotList) Descriptor() ([]byte, []int) {
	return file_goods_proto_rawDescGZIP(), []int{35}
}

func (x *HotList) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *HotList) GetBrandName() string {
	if x != nil {
		return x.BrandName
	}
	return ""
}

func (x *HotList) GetHot() int64 {
	if x != nil {
		return x.Hot
	}
	return 0
}

var File_goods_proto protoreflect.FileDescriptor

var file_goods_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x53, 0x0a, 0x0d, 0x41, 0x64, 0x64, 0x53, 0x68, 0x6f, 0x70, 0x43,
	0x61, 0x72, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x18, 0x0a,
	0x07, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07,
	0x47, 0x6f, 0x6f, 0x64, 0x73, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x4e, 0x75, 0x6d, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x4e, 0x75, 0x6d, 0x22, 0x10, 0x0a, 0x0e, 0x41, 0x64, 0x64,
	0x53, 0x68, 0x6f, 0x70, 0x43, 0x61, 0x72, 0x52, 0x65, 0x73, 0x70, 0x22, 0x44, 0x0a, 0x10, 0x41,
	0x64, 0x64, 0x53, 0x68, 0x6f, 0x70, 0x43, 0x61, 0x72, 0x4e, 0x75, 0x6d, 0x52, 0x65, 0x71, 0x12,
	0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x47, 0x6f, 0x6f, 0x64, 0x73,
	0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x49,
	0x64, 0x22, 0x13, 0x0a, 0x11, 0x41, 0x64, 0x64, 0x53, 0x68, 0x6f, 0x70, 0x43, 0x61, 0x72, 0x4e,
	0x75, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x22, 0x44, 0x0a, 0x10, 0x50, 0x6f, 0x70, 0x53, 0x68, 0x6f,
	0x70, 0x43, 0x61, 0x72, 0x4e, 0x75, 0x6d, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73,
	0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72,
	0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x49, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x07, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x49, 0x64, 0x22, 0x13, 0x0a, 0x11,
	0x50, 0x6f, 0x70, 0x53, 0x68, 0x6f, 0x70, 0x43, 0x61, 0x72, 0x4e, 0x75, 0x6d, 0x52, 0x65, 0x73,
	0x70, 0x22, 0x59, 0x0a, 0x13, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x68, 0x6f, 0x70, 0x43,
	0x61, 0x72, 0x4e, 0x75, 0x6d, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72,
	0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64,
	0x12, 0x18, 0x0a, 0x07, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x07, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x4e, 0x75,
	0x6d, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x4e, 0x75, 0x6d, 0x22, 0x16, 0x0a, 0x14,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x68, 0x6f, 0x70, 0x43, 0x61, 0x72, 0x4e, 0x75, 0x6d,
	0x52, 0x65, 0x73, 0x70, 0x22, 0x29, 0x0a, 0x0f, 0x43, 0x6c, 0x65, 0x61, 0x6e, 0x53, 0x68, 0x6f,
	0x70, 0x43, 0x61, 0x72, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22,
	0x12, 0x0a, 0x10, 0x43, 0x6c, 0x65, 0x61, 0x6e, 0x53, 0x68, 0x6f, 0x70, 0x43, 0x61, 0x72, 0x52,
	0x65, 0x73, 0x70, 0x22, 0x2f, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x53, 0x68, 0x6f, 0x70, 0x43, 0x61,
	0x72, 0x41, 0x6c, 0x6c, 0x50, 0x72, 0x69, 0x63, 0x65, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06,
	0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73,
	0x65, 0x72, 0x49, 0x64, 0x22, 0x2e, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x53, 0x68, 0x6f, 0x70, 0x43,
	0x61, 0x72, 0x41, 0x6c, 0x6c, 0x50, 0x72, 0x69, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x14,
	0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x05, 0x70,
	0x72, 0x69, 0x63, 0x65, 0x22, 0xa7, 0x02, 0x0a, 0x0b, 0x53, 0x68, 0x6f, 0x70, 0x43, 0x61, 0x72,
	0x4c, 0x69, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x4e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x4e, 0x61,
	0x6d, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x50, 0x72, 0x69, 0x63, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x0a, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x50, 0x72, 0x69,
	0x63, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x67, 0x72, 0x61, 0x6e, 0x64, 0x4e, 0x61, 0x6d, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x67, 0x72, 0x61, 0x6e, 0x64, 0x4e, 0x61, 0x6d, 0x65,
	0x12, 0x1a, 0x0a, 0x08, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x55, 0x72, 0x6c, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x55, 0x72, 0x6c, 0x12, 0x1c, 0x0a, 0x09,
	0x67, 0x6f, 0x6f, 0x64, 0x73, 0x44, 0x65, 0x73, 0x63, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x44, 0x65, 0x73, 0x63, 0x12, 0x10, 0x0a, 0x03, 0x6e, 0x75,
	0x6d, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x6e, 0x75, 0x6d, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08,
	0x73, 0x68, 0x6f, 0x70, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x73, 0x68, 0x6f, 0x70, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x6c, 0x6f,
	0x72, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x12, 0x12,
	0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x73, 0x69,
	0x7a, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x6d, 0x61, 0x74, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x18, 0x0c,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6d, 0x61, 0x74, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x22, 0x2c,
	0x0a, 0x12, 0x55, 0x73, 0x65, 0x72, 0x53, 0x68, 0x6f, 0x70, 0x43, 0x61, 0x72, 0x4c, 0x69, 0x73,
	0x74, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x3d, 0x0a, 0x13,
	0x55, 0x73, 0x65, 0x72, 0x53, 0x68, 0x6f, 0x70, 0x43, 0x61, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x12, 0x26, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x12, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x68, 0x6f, 0x70, 0x43, 0x61,
	0x72, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x22, 0x48, 0x0a, 0x1a, 0x55,
	0x73, 0x65, 0x72, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x53, 0x68, 0x6f, 0x70, 0x43, 0x61, 0x72,
	0x42, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a,
	0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75,
	0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x45, 0x0a, 0x1b, 0x55, 0x73, 0x65, 0x72, 0x53, 0x65, 0x61,
	0x72, 0x63, 0x68, 0x53, 0x68, 0x6f, 0x70, 0x43, 0x61, 0x72, 0x42, 0x79, 0x4e, 0x61, 0x6d, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x12, 0x26, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x12, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x68, 0x6f, 0x70, 0x43,
	0x61, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x22, 0x48, 0x0a, 0x14,
	0x44, 0x65, 0x6c, 0x4f, 0x6e, 0x65, 0x53, 0x68, 0x6f, 0x70, 0x43, 0x61, 0x72, 0x44, 0x61, 0x74,
	0x61, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07,
	0x47, 0x6f, 0x6f, 0x64, 0x73, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x47,
	0x6f, 0x6f, 0x64, 0x73, 0x49, 0x64, 0x22, 0x17, 0x0a, 0x15, 0x44, 0x65, 0x6c, 0x4f, 0x6e, 0x65,
	0x53, 0x68, 0x6f, 0x70, 0x43, 0x61, 0x72, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x73, 0x70, 0x22,
	0x68, 0x0a, 0x18, 0x57, 0x65, 0x6c, 0x63, 0x6f, 0x6d, 0x65, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68,
	0x53, 0x68, 0x6f, 0x70, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x12, 0x1c, 0x0a, 0x09, 0x62,
	0x72, 0x61, 0x6e, 0x64, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x62, 0x72, 0x61, 0x6e, 0x64, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x12, 0x1a, 0x0a,
	0x08, 0x70, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x08, 0x70, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x22, 0x4d, 0x0a, 0x19, 0x57, 0x65, 0x6c,
	0x63, 0x6f, 0x6d, 0x65, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x53, 0x68, 0x6f, 0x70, 0x4c, 0x69,
	0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x30, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x57, 0x65, 0x6c,
	0x63, 0x6f, 0x6d, 0x65, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x53, 0x68, 0x6f, 0x70, 0x4c, 0x69,
	0x73, 0x74, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x22, 0xcf, 0x02, 0x0a, 0x15, 0x57, 0x65, 0x6c,
	0x63, 0x6f, 0x6d, 0x65, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x53, 0x68, 0x6f, 0x70, 0x4c, 0x69,
	0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x42, 0x72, 0x61, 0x6e, 0x64, 0x4c, 0x6f, 0x67, 0x6f, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x42, 0x72, 0x61, 0x6e, 0x64, 0x4c, 0x6f, 0x67, 0x6f,
	0x12, 0x1c, 0x0a, 0x09, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x2a,
	0x0a, 0x10, 0x42, 0x72, 0x61, 0x6e, 0x64, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x42, 0x72, 0x61, 0x6e, 0x64, 0x44,
	0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1e, 0x0a, 0x0a, 0x47, 0x6f,
	0x6f, 0x64, 0x73, 0x50, 0x72, 0x69, 0x63, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x02, 0x52, 0x0a,
	0x47, 0x6f, 0x6f, 0x64, 0x73, 0x50, 0x72, 0x69, 0x63, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x42, 0x72,
	0x61, 0x6e, 0x64, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x42,
	0x72, 0x61, 0x6e, 0x64, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x47, 0x6f, 0x6f, 0x64,
	0x73, 0x55, 0x72, 0x6c, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x47, 0x6f, 0x6f, 0x64,
	0x73, 0x55, 0x72, 0x6c, 0x12, 0x1c, 0x0a, 0x09, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x44, 0x65, 0x73,
	0x63, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x44, 0x65,
	0x73, 0x63, 0x12, 0x1e, 0x0a, 0x0a, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x53, 0x74, 0x6f, 0x63, 0x6b,
	0x18, 0x08, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x53, 0x74, 0x6f,
	0x63, 0x6b, 0x12, 0x20, 0x0a, 0x0b, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x18, 0x09, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x53, 0x61, 0x6c, 0x65, 0x73, 0x18, 0x0a, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x05, 0x53, 0x61, 0x6c, 0x65, 0x73, 0x22, 0x2b, 0x0a, 0x0e, 0x47, 0x6f,
	0x6f, 0x64, 0x73, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x71, 0x12, 0x19, 0x0a, 0x08,
	0x67, 0x6f, 0x6f, 0x64, 0x73, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07,
	0x67, 0x6f, 0x6f, 0x64, 0x73, 0x49, 0x64, 0x22, 0x47, 0x0a, 0x0f, 0x47, 0x6f, 0x6f, 0x64, 0x73,
	0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x12, 0x34, 0x0a, 0x0b, 0x67, 0x6f,
	0x6f, 0x64, 0x73, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x12, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x44, 0x65, 0x74,
	0x61, 0x69, 0x6c, 0x52, 0x0b, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c,
	0x22, 0xc7, 0x01, 0x0a, 0x0b, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c,
	0x12, 0x19, 0x0a, 0x08, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x07, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x67,
	0x6f, 0x6f, 0x64, 0x73, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x67, 0x6f,
	0x6f, 0x64, 0x73, 0x5f, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52,
	0x0a, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x50, 0x72, 0x69, 0x63, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x67,
	0x6f, 0x6f, 0x64, 0x73, 0x5f, 0x64, 0x65, 0x73, 0x63, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x44, 0x65, 0x73, 0x63, 0x12, 0x1b, 0x0a, 0x09, 0x69, 0x6d,
	0x61, 0x67, 0x65, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x69,
	0x6d, 0x61, 0x67, 0x65, 0x55, 0x72, 0x6c, 0x12, 0x21, 0x0a, 0x0c, 0x73, 0x6c, 0x69, 0x64, 0x65,
	0x72, 0x5f, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x73,
	0x6c, 0x69, 0x64, 0x65, 0x72, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x22, 0x2a, 0x0a, 0x0d, 0x53, 0x68,
	0x6f, 0x70, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x71, 0x12, 0x19, 0x0a, 0x08, 0x67,
	0x6f, 0x6f, 0x64, 0x73, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x67,
	0x6f, 0x6f, 0x64, 0x73, 0x49, 0x64, 0x22, 0x43, 0x0a, 0x0e, 0x53, 0x68, 0x6f, 0x70, 0x44, 0x65,
	0x74, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x12, 0x31, 0x0a, 0x0a, 0x73, 0x68, 0x6f, 0x70,
	0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x68, 0x6f, 0x70, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52,
	0x0a, 0x73, 0x68, 0x6f, 0x70, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x22, 0x80, 0x03, 0x0a, 0x0a,
	0x53, 0x68, 0x6f, 0x70, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x12, 0x19, 0x0a, 0x08, 0x67, 0x6f,
	0x6f, 0x64, 0x73, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x67, 0x6f,
	0x6f, 0x64, 0x73, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x5f, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x67, 0x6f, 0x6f, 0x64, 0x73,
	0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x5f, 0x70, 0x72,
	0x69, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x0a, 0x67, 0x6f, 0x6f, 0x64, 0x73,
	0x50, 0x72, 0x69, 0x63, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x5f, 0x64,
	0x65, 0x73, 0x63, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x67, 0x6f, 0x6f, 0x64, 0x73,
	0x44, 0x65, 0x73, 0x63, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x68, 0x6f, 0x70, 0x5f, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x68, 0x6f, 0x70, 0x4e, 0x61, 0x6d,
	0x65, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x68, 0x6f, 0x70, 0x5f, 0x64, 0x65, 0x73, 0x63, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x68, 0x6f, 0x70, 0x44, 0x65, 0x73, 0x63, 0x12, 0x1b,
	0x0a, 0x09, 0x73, 0x68, 0x6f, 0x70, 0x5f, 0x6c, 0x6f, 0x67, 0x6f, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x73, 0x68, 0x6f, 0x70, 0x4c, 0x6f, 0x67, 0x6f, 0x12, 0x1d, 0x0a, 0x0a, 0x73,
	0x68, 0x6f, 0x70, 0x5f, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x73, 0x68, 0x6f, 0x70, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x73, 0x68,
	0x6f, 0x70, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x73, 0x68, 0x6f, 0x70, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x1f, 0x0a,
	0x0b, 0x73, 0x68, 0x6f, 0x70, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x0a, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0a, 0x73, 0x68, 0x6f, 0x70, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1b,
	0x0a, 0x09, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x0b, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x55, 0x72, 0x6c, 0x12, 0x21, 0x0a, 0x0c, 0x73,
	0x6c, 0x69, 0x64, 0x65, 0x72, 0x5f, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x18, 0x0c, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0b, 0x73, 0x6c, 0x69, 0x64, 0x65, 0x72, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x22, 0x0e,
	0x0a, 0x0c, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x50, 0x75, 0x73, 0x68, 0x52, 0x65, 0x71, 0x22, 0x35,
	0x0a, 0x0d, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x50, 0x75, 0x73, 0x68, 0x52, 0x65, 0x73, 0x70, 0x12,
	0x24, 0x0a, 0x04, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x50, 0x75, 0x73, 0x68, 0x52,
	0x04, 0x4c, 0x69, 0x73, 0x74, 0x22, 0xfa, 0x01, 0x0a, 0x09, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x50,
	0x75, 0x73, 0x68, 0x12, 0x19, 0x0a, 0x08, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x49, 0x64, 0x12, 0x1d,
	0x0a, 0x0a, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1f, 0x0a,
	0x0b, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x5f, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x02, 0x52, 0x0a, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x50, 0x72, 0x69, 0x63, 0x65, 0x12, 0x1d,
	0x0a, 0x0a, 0x62, 0x72, 0x61, 0x6e, 0x64, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x62, 0x72, 0x61, 0x6e, 0x64, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1b, 0x0a,
	0x09, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x55, 0x72, 0x6c, 0x12, 0x21, 0x0a, 0x0c, 0x73, 0x6c,
	0x69, 0x64, 0x65, 0x72, 0x5f, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x73, 0x6c, 0x69, 0x64, 0x65, 0x72, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x12, 0x14, 0x0a,
	0x05, 0x73, 0x61, 0x6c, 0x65, 0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x73, 0x61,
	0x6c, 0x65, 0x73, 0x12, 0x1d, 0x0a, 0x0a, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x5f, 0x64, 0x65, 0x73,
	0x63, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x44, 0x65,
	0x73, 0x63, 0x22, 0x22, 0x0a, 0x10, 0x57, 0x65, 0x6c, 0x63, 0x6f, 0x6d, 0x65, 0x53, 0x65, 0x61,
	0x72, 0x63, 0x68, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x22, 0x8b, 0x01, 0x0a, 0x11, 0x57, 0x65, 0x6c, 0x63, 0x6f,
	0x6d, 0x65, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x52, 0x65, 0x73, 0x70, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1c, 0x0a, 0x09,
	0x62, 0x72, 0x61, 0x6e, 0x64, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x62, 0x72, 0x61, 0x6e, 0x64, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x62, 0x72,
	0x61, 0x6e, 0x64, 0x4c, 0x6f, 0x67, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x62,
	0x72, 0x61, 0x6e, 0x64, 0x4c, 0x6f, 0x67, 0x6f, 0x12, 0x2a, 0x0a, 0x10, 0x62, 0x72, 0x61, 0x6e,
	0x64, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x10, 0x62, 0x72, 0x61, 0x6e, 0x64, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x22, 0x24, 0x0a, 0x0c, 0x48, 0x6f, 0x74, 0x53, 0x65, 0x61, 0x72, 0x63,
	0x68, 0x52, 0x65, 0x71, 0x12, 0x14, 0x0a, 0x05, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x05, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x22, 0x33, 0x0a, 0x0d, 0x48, 0x6f,
	0x74, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x52, 0x65, 0x73, 0x70, 0x12, 0x22, 0x0a, 0x04, 0x6c,
	0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x48, 0x6f, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x22,
	0x49, 0x0a, 0x07, 0x48, 0x6f, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x62, 0x72,
	0x61, 0x6e, 0x64, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x62,
	0x72, 0x61, 0x6e, 0x64, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x68, 0x6f, 0x74, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x68, 0x6f, 0x74, 0x32, 0xb0, 0x08, 0x0a, 0x05, 0x47,
	0x6f, 0x6f, 0x64, 0x73, 0x12, 0x39, 0x0a, 0x0a, 0x41, 0x64, 0x64, 0x53, 0x68, 0x6f, 0x70, 0x43,
	0x61, 0x72, 0x12, 0x14, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x41, 0x64, 0x64, 0x53, 0x68,
	0x6f, 0x70, 0x43, 0x61, 0x72, 0x52, 0x65, 0x71, 0x1a, 0x15, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x41, 0x64, 0x64, 0x53, 0x68, 0x6f, 0x70, 0x43, 0x61, 0x72, 0x52, 0x65, 0x73, 0x70, 0x12,
	0x42, 0x0a, 0x0d, 0x41, 0x64, 0x64, 0x53, 0x68, 0x6f, 0x70, 0x43, 0x61, 0x72, 0x4e, 0x75, 0x6d,
	0x12, 0x17, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x41, 0x64, 0x64, 0x53, 0x68, 0x6f, 0x70,
	0x43, 0x61, 0x72, 0x4e, 0x75, 0x6d, 0x52, 0x65, 0x71, 0x1a, 0x18, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x41, 0x64, 0x64, 0x53, 0x68, 0x6f, 0x70, 0x43, 0x61, 0x72, 0x4e, 0x75, 0x6d, 0x52,
	0x65, 0x73, 0x70, 0x12, 0x42, 0x0a, 0x0d, 0x50, 0x6f, 0x70, 0x53, 0x68, 0x6f, 0x70, 0x43, 0x61,
	0x72, 0x4e, 0x75, 0x6d, 0x12, 0x17, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x6f, 0x70,
	0x53, 0x68, 0x6f, 0x70, 0x43, 0x61, 0x72, 0x4e, 0x75, 0x6d, 0x52, 0x65, 0x71, 0x1a, 0x18, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x6f, 0x70, 0x53, 0x68, 0x6f, 0x70, 0x43, 0x61, 0x72,
	0x4e, 0x75, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x12, 0x3f, 0x0a, 0x0c, 0x43, 0x6c, 0x65, 0x61, 0x6e,
	0x53, 0x68, 0x6f, 0x70, 0x43, 0x61, 0x72, 0x12, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x43, 0x6c, 0x65, 0x61, 0x6e, 0x53, 0x68, 0x6f, 0x70, 0x43, 0x61, 0x72, 0x52, 0x65, 0x71, 0x1a,
	0x17, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x6c, 0x65, 0x61, 0x6e, 0x53, 0x68, 0x6f,
	0x70, 0x43, 0x61, 0x72, 0x52, 0x65, 0x73, 0x70, 0x12, 0x4b, 0x0a, 0x10, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x53, 0x68, 0x6f, 0x70, 0x43, 0x61, 0x72, 0x4e, 0x75, 0x6d, 0x12, 0x1a, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x68, 0x6f, 0x70, 0x43,
	0x61, 0x72, 0x4e, 0x75, 0x6d, 0x52, 0x65, 0x71, 0x1a, 0x1b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x68, 0x6f, 0x70, 0x43, 0x61, 0x72, 0x4e, 0x75,
	0x6d, 0x52, 0x65, 0x73, 0x70, 0x12, 0x51, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x53, 0x68, 0x6f, 0x70,
	0x43, 0x61, 0x72, 0x41, 0x6c, 0x6c, 0x50, 0x72, 0x69, 0x63, 0x65, 0x12, 0x1c, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x68, 0x6f, 0x70, 0x43, 0x61, 0x72, 0x41, 0x6c,
	0x6c, 0x50, 0x72, 0x69, 0x63, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x1d, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x68, 0x6f, 0x70, 0x43, 0x61, 0x72, 0x41, 0x6c, 0x6c, 0x50,
	0x72, 0x69, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x48, 0x0a, 0x0f, 0x55, 0x73, 0x65, 0x72,
	0x53, 0x68, 0x6f, 0x70, 0x43, 0x61, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x19, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x53, 0x68, 0x6f, 0x70, 0x43, 0x61, 0x72, 0x4c,
	0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x1a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x55,
	0x73, 0x65, 0x72, 0x53, 0x68, 0x6f, 0x70, 0x43, 0x61, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x12, 0x60, 0x0a, 0x17, 0x55, 0x73, 0x65, 0x72, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68,
	0x53, 0x68, 0x6f, 0x70, 0x43, 0x61, 0x72, 0x42, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x21, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68,
	0x53, 0x68, 0x6f, 0x70, 0x43, 0x61, 0x72, 0x42, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x71,
	0x1a, 0x22, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x53, 0x65, 0x61,
	0x72, 0x63, 0x68, 0x53, 0x68, 0x6f, 0x70, 0x43, 0x61, 0x72, 0x42, 0x79, 0x4e, 0x61, 0x6d, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x12, 0x4e, 0x0a, 0x11, 0x44, 0x65, 0x6c, 0x4f, 0x6e, 0x65, 0x53, 0x68,
	0x6f, 0x70, 0x43, 0x61, 0x72, 0x44, 0x61, 0x74, 0x61, 0x12, 0x1b, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x44, 0x65, 0x6c, 0x4f, 0x6e, 0x65, 0x53, 0x68, 0x6f, 0x70, 0x43, 0x61, 0x72, 0x44,
	0x61, 0x74, 0x61, 0x52, 0x65, 0x71, 0x1a, 0x1c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x44,
	0x65, 0x6c, 0x4f, 0x6e, 0x65, 0x53, 0x68, 0x6f, 0x70, 0x43, 0x61, 0x72, 0x44, 0x61, 0x74, 0x61,
	0x52, 0x65, 0x73, 0x70, 0x12, 0x5a, 0x0a, 0x15, 0x57, 0x65, 0x6c, 0x63, 0x6f, 0x6d, 0x65, 0x53,
	0x65, 0x61, 0x72, 0x63, 0x68, 0x53, 0x68, 0x6f, 0x70, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x1f, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x57, 0x65, 0x6c, 0x63, 0x6f, 0x6d, 0x65, 0x53, 0x65, 0x61,
	0x72, 0x63, 0x68, 0x53, 0x68, 0x6f, 0x70, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x20,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x57, 0x65, 0x6c, 0x63, 0x6f, 0x6d, 0x65, 0x53, 0x65,
	0x61, 0x72, 0x63, 0x68, 0x53, 0x68, 0x6f, 0x70, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x12, 0x3c, 0x0a, 0x0b, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x12,
	0x15, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x44, 0x65, 0x74,
	0x61, 0x69, 0x6c, 0x52, 0x65, 0x71, 0x1a, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47,
	0x6f, 0x6f, 0x64, 0x73, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x12, 0x39,
	0x0a, 0x0a, 0x53, 0x68, 0x6f, 0x70, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x12, 0x14, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x68, 0x6f, 0x70, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52,
	0x65, 0x71, 0x1a, 0x15, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x68, 0x6f, 0x70, 0x44,
	0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x12, 0x36, 0x0a, 0x09, 0x47, 0x6f, 0x6f,
	0x64, 0x73, 0x50, 0x75, 0x73, 0x68, 0x12, 0x13, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47,
	0x6f, 0x6f, 0x64, 0x73, 0x50, 0x75, 0x73, 0x68, 0x52, 0x65, 0x71, 0x1a, 0x14, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x50, 0x75, 0x73, 0x68, 0x52, 0x65, 0x73,
	0x70, 0x12, 0x42, 0x0a, 0x0d, 0x57, 0x65, 0x6c, 0x63, 0x6f, 0x6d, 0x65, 0x53, 0x65, 0x61, 0x72,
	0x63, 0x68, 0x12, 0x17, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x57, 0x65, 0x6c, 0x63, 0x6f,
	0x6d, 0x65, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x52, 0x65, 0x71, 0x1a, 0x18, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x57, 0x65, 0x6c, 0x63, 0x6f, 0x6d, 0x65, 0x53, 0x65, 0x61, 0x72, 0x63,
	0x68, 0x52, 0x65, 0x73, 0x70, 0x12, 0x36, 0x0a, 0x09, 0x48, 0x6f, 0x74, 0x53, 0x65, 0x61, 0x72,
	0x63, 0x68, 0x12, 0x13, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x48, 0x6f, 0x74, 0x53, 0x65,
	0x61, 0x72, 0x63, 0x68, 0x52, 0x65, 0x71, 0x1a, 0x14, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x48, 0x6f, 0x74, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x52, 0x65, 0x73, 0x70, 0x42, 0x04, 0x5a,
	0x02, 0x2e, 0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_goods_proto_rawDescOnce sync.Once
	file_goods_proto_rawDescData = file_goods_proto_rawDesc
)

func file_goods_proto_rawDescGZIP() []byte {
	file_goods_proto_rawDescOnce.Do(func() {
		file_goods_proto_rawDescData = protoimpl.X.CompressGZIP(file_goods_proto_rawDescData)
	})
	return file_goods_proto_rawDescData
}

var file_goods_proto_msgTypes = make([]protoimpl.MessageInfo, 36)
var file_goods_proto_goTypes = []any{
	(*AddShopCarReq)(nil),               // 0: proto.AddShopCarReq
	(*AddShopCarResp)(nil),              // 1: proto.AddShopCarResp
	(*AddShopCarNumReq)(nil),            // 2: proto.AddShopCarNumReq
	(*AddShopCarNumResp)(nil),           // 3: proto.AddShopCarNumResp
	(*PopShopCarNumReq)(nil),            // 4: proto.PopShopCarNumReq
	(*PopShopCarNumResp)(nil),           // 5: proto.PopShopCarNumResp
	(*UpdateShopCarNumReq)(nil),         // 6: proto.UpdateShopCarNumReq
	(*UpdateShopCarNumResp)(nil),        // 7: proto.UpdateShopCarNumResp
	(*CleanShopCarReq)(nil),             // 8: proto.CleanShopCarReq
	(*CleanShopCarResp)(nil),            // 9: proto.CleanShopCarResp
	(*GetShopCarAllPriceReq)(nil),       // 10: proto.GetShopCarAllPriceReq
	(*GetShopCarAllPriceResp)(nil),      // 11: proto.GetShopCarAllPriceResp
	(*ShopCarList)(nil),                 // 12: proto.ShopCarList
	(*UserShopCarListReq)(nil),          // 13: proto.UserShopCarListReq
	(*UserShopCarListResp)(nil),         // 14: proto.UserShopCarListResp
	(*UserSearchShopCarByNameReq)(nil),  // 15: proto.UserSearchShopCarByNameReq
	(*UserSearchShopCarByNameResp)(nil), // 16: proto.UserSearchShopCarByNameResp
	(*DelOneShopCarDataReq)(nil),        // 17: proto.DelOneShopCarDataReq
	(*DelOneShopCarDataResp)(nil),       // 18: proto.DelOneShopCarDataResp
	(*WelcomeSearchShopListReq)(nil),    // 19: proto.WelcomeSearchShopListReq
	(*WelcomeSearchShopListResp)(nil),   // 20: proto.WelcomeSearchShopListResp
	(*WelcomeSearchShopList)(nil),       // 21: proto.WelcomeSearchShopList
	(*GoodsDetailReq)(nil),              // 22: proto.GoodsDetailReq
	(*GoodsDetailResp)(nil),             // 23: proto.GoodsDetailResp
	(*GoodsDetail)(nil),                 // 24: proto.GoodsDetail
	(*ShopDetailReq)(nil),               // 25: proto.ShopDetailReq
	(*ShopDetailResp)(nil),              // 26: proto.ShopDetailResp
	(*ShopDetail)(nil),                  // 27: proto.ShopDetail
	(*GoodsPushReq)(nil),                // 28: proto.GoodsPushReq
	(*GoodsPushResp)(nil),               // 29: proto.GoodsPushResp
	(*GoodsPush)(nil),                   // 30: proto.GoodsPush
	(*WelcomeSearchReq)(nil),            // 31: proto.WelcomeSearchReq
	(*WelcomeSearchResp)(nil),           // 32: proto.WelcomeSearchResp
	(*HotSearchReq)(nil),                // 33: proto.HotSearchReq
	(*HotSearchResp)(nil),               // 34: proto.HotSearchResp
	(*HotList)(nil),                     // 35: proto.HotList
}
var file_goods_proto_depIdxs = []int32{
	12, // 0: proto.UserShopCarListResp.list:type_name -> proto.ShopCarList
	12, // 1: proto.UserSearchShopCarByNameResp.list:type_name -> proto.ShopCarList
	21, // 2: proto.WelcomeSearchShopListResp.list:type_name -> proto.WelcomeSearchShopList
	24, // 3: proto.GoodsDetailResp.goodsDetail:type_name -> proto.GoodsDetail
	27, // 4: proto.ShopDetailResp.shopDetail:type_name -> proto.ShopDetail
	30, // 5: proto.GoodsPushResp.List:type_name -> proto.GoodsPush
	35, // 6: proto.HotSearchResp.list:type_name -> proto.HotList
	0,  // 7: proto.Goods.AddShopCar:input_type -> proto.AddShopCarReq
	2,  // 8: proto.Goods.AddShopCarNum:input_type -> proto.AddShopCarNumReq
	4,  // 9: proto.Goods.PopShopCarNum:input_type -> proto.PopShopCarNumReq
	8,  // 10: proto.Goods.CleanShopCar:input_type -> proto.CleanShopCarReq
	6,  // 11: proto.Goods.UpdateShopCarNum:input_type -> proto.UpdateShopCarNumReq
	10, // 12: proto.Goods.GetShopCarAllPrice:input_type -> proto.GetShopCarAllPriceReq
	13, // 13: proto.Goods.UserShopCarList:input_type -> proto.UserShopCarListReq
	15, // 14: proto.Goods.UserSearchShopCarByName:input_type -> proto.UserSearchShopCarByNameReq
	17, // 15: proto.Goods.DelOneShopCarData:input_type -> proto.DelOneShopCarDataReq
	19, // 16: proto.Goods.WelcomeSearchShopList:input_type -> proto.WelcomeSearchShopListReq
	22, // 17: proto.Goods.GoodsDetail:input_type -> proto.GoodsDetailReq
	25, // 18: proto.Goods.ShopDetail:input_type -> proto.ShopDetailReq
	28, // 19: proto.Goods.GoodsPush:input_type -> proto.GoodsPushReq
	31, // 20: proto.Goods.WelcomeSearch:input_type -> proto.WelcomeSearchReq
	33, // 21: proto.Goods.HotSearch:input_type -> proto.HotSearchReq
	1,  // 22: proto.Goods.AddShopCar:output_type -> proto.AddShopCarResp
	3,  // 23: proto.Goods.AddShopCarNum:output_type -> proto.AddShopCarNumResp
	5,  // 24: proto.Goods.PopShopCarNum:output_type -> proto.PopShopCarNumResp
	9,  // 25: proto.Goods.CleanShopCar:output_type -> proto.CleanShopCarResp
	7,  // 26: proto.Goods.UpdateShopCarNum:output_type -> proto.UpdateShopCarNumResp
	11, // 27: proto.Goods.GetShopCarAllPrice:output_type -> proto.GetShopCarAllPriceResp
	14, // 28: proto.Goods.UserShopCarList:output_type -> proto.UserShopCarListResp
	16, // 29: proto.Goods.UserSearchShopCarByName:output_type -> proto.UserSearchShopCarByNameResp
	18, // 30: proto.Goods.DelOneShopCarData:output_type -> proto.DelOneShopCarDataResp
	20, // 31: proto.Goods.WelcomeSearchShopList:output_type -> proto.WelcomeSearchShopListResp
	23, // 32: proto.Goods.GoodsDetail:output_type -> proto.GoodsDetailResp
	26, // 33: proto.Goods.ShopDetail:output_type -> proto.ShopDetailResp
	29, // 34: proto.Goods.GoodsPush:output_type -> proto.GoodsPushResp
	32, // 35: proto.Goods.WelcomeSearch:output_type -> proto.WelcomeSearchResp
	34, // 36: proto.Goods.HotSearch:output_type -> proto.HotSearchResp
	22, // [22:37] is the sub-list for method output_type
	7,  // [7:22] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_goods_proto_init() }
func file_goods_proto_init() {
	if File_goods_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_goods_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*AddShopCarReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_goods_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*AddShopCarResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_goods_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*AddShopCarNumReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_goods_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*AddShopCarNumResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_goods_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*PopShopCarNumReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_goods_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*PopShopCarNumResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_goods_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*UpdateShopCarNumReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_goods_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*UpdateShopCarNumResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_goods_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*CleanShopCarReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_goods_proto_msgTypes[9].Exporter = func(v any, i int) any {
			switch v := v.(*CleanShopCarResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_goods_proto_msgTypes[10].Exporter = func(v any, i int) any {
			switch v := v.(*GetShopCarAllPriceReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_goods_proto_msgTypes[11].Exporter = func(v any, i int) any {
			switch v := v.(*GetShopCarAllPriceResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_goods_proto_msgTypes[12].Exporter = func(v any, i int) any {
			switch v := v.(*ShopCarList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_goods_proto_msgTypes[13].Exporter = func(v any, i int) any {
			switch v := v.(*UserShopCarListReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_goods_proto_msgTypes[14].Exporter = func(v any, i int) any {
			switch v := v.(*UserShopCarListResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_goods_proto_msgTypes[15].Exporter = func(v any, i int) any {
			switch v := v.(*UserSearchShopCarByNameReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_goods_proto_msgTypes[16].Exporter = func(v any, i int) any {
			switch v := v.(*UserSearchShopCarByNameResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_goods_proto_msgTypes[17].Exporter = func(v any, i int) any {
			switch v := v.(*DelOneShopCarDataReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_goods_proto_msgTypes[18].Exporter = func(v any, i int) any {
			switch v := v.(*DelOneShopCarDataResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_goods_proto_msgTypes[19].Exporter = func(v any, i int) any {
			switch v := v.(*WelcomeSearchShopListReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_goods_proto_msgTypes[20].Exporter = func(v any, i int) any {
			switch v := v.(*WelcomeSearchShopListResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_goods_proto_msgTypes[21].Exporter = func(v any, i int) any {
			switch v := v.(*WelcomeSearchShopList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_goods_proto_msgTypes[22].Exporter = func(v any, i int) any {
			switch v := v.(*GoodsDetailReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_goods_proto_msgTypes[23].Exporter = func(v any, i int) any {
			switch v := v.(*GoodsDetailResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_goods_proto_msgTypes[24].Exporter = func(v any, i int) any {
			switch v := v.(*GoodsDetail); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_goods_proto_msgTypes[25].Exporter = func(v any, i int) any {
			switch v := v.(*ShopDetailReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_goods_proto_msgTypes[26].Exporter = func(v any, i int) any {
			switch v := v.(*ShopDetailResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_goods_proto_msgTypes[27].Exporter = func(v any, i int) any {
			switch v := v.(*ShopDetail); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_goods_proto_msgTypes[28].Exporter = func(v any, i int) any {
			switch v := v.(*GoodsPushReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_goods_proto_msgTypes[29].Exporter = func(v any, i int) any {
			switch v := v.(*GoodsPushResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_goods_proto_msgTypes[30].Exporter = func(v any, i int) any {
			switch v := v.(*GoodsPush); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_goods_proto_msgTypes[31].Exporter = func(v any, i int) any {
			switch v := v.(*WelcomeSearchReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_goods_proto_msgTypes[32].Exporter = func(v any, i int) any {
			switch v := v.(*WelcomeSearchResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_goods_proto_msgTypes[33].Exporter = func(v any, i int) any {
			switch v := v.(*HotSearchReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_goods_proto_msgTypes[34].Exporter = func(v any, i int) any {
			switch v := v.(*HotSearchResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_goods_proto_msgTypes[35].Exporter = func(v any, i int) any {
			switch v := v.(*HotList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_goods_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   36,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_goods_proto_goTypes,
		DependencyIndexes: file_goods_proto_depIdxs,
		MessageInfos:      file_goods_proto_msgTypes,
	}.Build()
	File_goods_proto = out.File
	file_goods_proto_rawDesc = nil
	file_goods_proto_goTypes = nil
	file_goods_proto_depIdxs = nil
}
